ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.beauty.ApplicationKt.module ]
    }
}

jwt {
    secret = "beauty_secret_jwt_key_2026_super_secure"
    issuer = "http://0.0.0.0:8080/"
    audience = "http://0.0.0.0:8080/users"
    realm = "Beauty Client Management"
}

db {
    driver = "org.postgresql.Driver"
    url = "jdbc:postgresql://localhost:5432/beautydb"
    user = "postgres"
    password = "postgrespassword"
}
